config/routes.rb
Rails.application.routes.draw do
    root to: "tasks#index"
    
    resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
      @tasks = Task.all
  end

  def show
      @task = Task.find(params[:id])
  end

  def new
      @task = Task.new
  end

  def edit
      @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>id: 
<%= @task.id %>
 のタスク編集ページ</h1>

<%= form_with(model: @task, local: true) do |f| %>

  
<%= f.label :content, 'タスク' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>

<% end %>


<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  
<% @tasks.each do |task| %>

    <li>
<%= link_to task.id, task %>
 :
<%= task.content %>
</li>
  
<% end %>

</ul>

<%= link_to '新規タスクの投稿', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= form_with(model: @task, local: true) do |f| %>

  
<%= f.label :content, 'タスク' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>

<% end %>


<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id: 
<%= @task.id %>
 のタスク詳細ページ</h1>

<p>
<%= @task.content %>
</p>

<%= link_to "一覧に戻る", tasks_path %>

<%= link_to "このタスクを編集する", edit_task_path(@task) %>